baseURL = "https://limubai404.github.io/"
languageCode = "zh-cn"
title = "我的测试博客"
theme = "PaperMod"

[params]
    defaultTheme = "dark"

    [params.homeInfoParams]
        Title = "欢迎 👋"
        Content = "这是一个测试页面。如果能看到它，就说明我们的网站部署成功了！"

[menu]
  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 10
